#!/bin/bash
# SPDX-License-Identifier: LGPL-2.1-or-later

# Private interface, subject to change, do not use.

set -ueo pipefail
context=$1
[[ "$context" == 'anaconda' ]]

exec fips-mode-setup --enable --no-bootcfg

# In the future, it should be reduced to just
# update-crypto-policies --set FIPS
