#!/bin/bash
# SPDX-License-Identifier: LGPL-2.1-or-later

# Private interface, subject to change, do not use.

set -ueo pipefail
context=$1

case "$context" in
    anaconda|coreos|cloud-init)
        exec update-crypto-policies --set FIPS
        ;;
    *)
        echo "fips-setup-helper: unknown context '$context'" >&2
        exit 1
        ;;
esac
